config/routes.rb
Rails.application.routes.draw do
  resources :walks

  resources :users

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/walk.rb
class Walk < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastname, :mobile)
    end
end

app/controllers/walks_controller.rb
class WalksController < ApplicationController
  before_action :set_walk, only: [:show, :edit, :update, :destroy]

  # GET /walks
  # GET /walks.json
  def index
    @walks = Walk.all
  end

  # GET /walks/1
  # GET /walks/1.json
  def show
  end

  # GET /walks/new
  def new
    @walk = Walk.new
  end

  # GET /walks/1/edit
  def edit
  end

  # POST /walks
  # POST /walks.json
  def create
    @walk = Walk.new(walk_params)

    respond_to do |format|
      if @walk.save
        format.html { redirect_to @walk, notice: 'Walk was successfully created.' }
        format.json { render :show, status: :created, location: @walk }
      else
        format.html { render :new }
        format.json { render json: @walk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /walks/1
  # PATCH/PUT /walks/1.json
  def update
    respond_to do |format|
      if @walk.update(walk_params)
        format.html { redirect_to @walk, notice: 'Walk was successfully updated.' }
        format.json { render :show, status: :ok, location: @walk }
      else
        format.html { render :edit }
        format.json { render json: @walk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /walks/1
  # DELETE /walks/1.json
  def destroy
    @walk.destroy
    respond_to do |format|
      format.html { redirect_to walks_url, notice: 'Walk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_walk
      @walk = Walk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def walk_params
      params.require(:walk).permit(:start, :distance, :calories, :speed, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/walks_helper.rb
module WalksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to 'Runkeeper', root_path %>
      </h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Sing up</a></li>
      <li>
        <a href="#">Sing in</a>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li>
        <%= link_to 'Users', users_path %>
        </li>
    </ul>
  </section>
</nav>
<div class="row">
  <div class="columns large-12">
     <%= yield %>
  </div>
</div>
   
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.number_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.mobile %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @user.mobile %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/walks/_form.html.erb
<%= form_for(@walk) do |f| %>
  <% if @walk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@walk.errors.count, "error") %> prohibited this walk from being saved:</h2>

      <ul>
      <% @walk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :distance %><br>
    <%= f.text_field :distance %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.number_field :calories %>
  </div>
  <div class="field">
    <%= f.label :speed %><br>
    <%= f.text_field :speed %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/walks/edit.html.erb
<h1>Editing walk</h1>

<%= render 'form' %>

<%= link_to 'Show', @walk %> |
<%= link_to 'Back', walks_path %>

app/views/walks/index.html.erb
<h1>Listing walks</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>Distance</th>
      <th>Calories</th>
      <th>Speed</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @walks.each do |walk| %>
      <tr>
        <td><%= walk.start %></td>
        <td><%= walk.distance %></td>
        <td><%= walk.calories %></td>
        <td><%= walk.speed %></td>
        <td><%= walk.user_id %></td>
        <td><%= link_to 'Show', walk %></td>
        <td><%= link_to 'Edit', edit_walk_path(walk) %></td>
        <td><%= link_to 'Destroy', walk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Walk', new_walk_path %>

app/views/walks/new.html.erb
<h1>New walk</h1>

<%= render 'form' %>

<%= link_to 'Back', walks_path %>

app/views/walks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @walk.start %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @walk.distance %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @walk.calories %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @walk.speed %>
</p>

<p>
  <strong>User:</strong>
  <%= @walk.user_id %>
</p>

<%= link_to 'Edit', edit_walk_path(@walk) %> |
<%= link_to 'Back', walks_path %>